version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_movie_reservation
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie_reservation_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - movie_reservation_network


volumes:
  postgres_data:

networks:
  movie_reservation_network: