spring:

  application:
    name: Movie Reservation System

  datasource:
    url: jdbc:postgresql://localhost:5432/movie_reservation_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

jwt: #adminadminadminadminadminadminadminadminadminadminadminadminadminadminadmin
  secret: YWRtaW5hZG1pbmFkbWluYWRtaW5hZG1pbmFkbWluYWRtaW5hZG1pbmFkbWluYWRtaW5hZG1pbmFkbWluYWRtaW5hZG1pbmFkbWlu
  expiration: 86400

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
